### ISSUE TITLE
Browser API link for v2.0.0 is not working

### ISSUE THREAD

**Issue by Rodrous** [k0d13/jswhat#2]
I've been trying to access the browerAPI link, but it doesn't exist for v2.0.0.
Although Link for v1.0.1 is working fine 
![image](https://user-images.githubusercontent.com/59244346/173289876-ce036c2c-4884-48ef-ab29-c00e9ca041ef.png)

**Comment by apteryxxyz** [comment]
Oh yeah, I haven't published v2 to NPM, I got busy with school.
The last time I touched this project, I was rewriting it in TypeScript, I'll see if I still have the code somewhere and publish it by at least tomorrow.

**Comment by apteryxxyz** [comment]
I've justed pushed and publish version 2.0.0, the module can be accessed in the browser using `https://unpkg.com/jswhat@2.0.0/dist/index.js`, let me know if you encounter any issues, cheers.
